SEEDIT_LOG -> log for easier merging

diff --git a/sources/functions/deluge b/sources/functions/deluge
--- a/sources/functions/deluge
+++ b/sources/functions/deluge
@@ -148,14 +148,14 @@ function build_libtorrent_rasterbar () {
 
     for depend in $LIST; do
       waitforapt
-      apt-get -qq -y install $depend >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..."; }
+      apt-get -qq -y install $depend >> "${log}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..."; }
     done
     install_fpm
     #OpenSSL 1.1.0 might fk a lot of things up -- Requires at least libboost-1.62 to build
     #if [[ ! ${codename} =~ ("xenial")|("yakkety") ]]; then
     #  LIST='libboost-system-dev libboost-python-dev libssl-dev libgeoip-dev libboost-chrono-dev libboost-random-dev'
     #  for depend in $LIST; do
-    #    apt-get -qq -y install $depend >> "${SEEDIT_LOG}"  2>&1
+    #    apt-get -qq -y install $depend >> "${log}"  2>&1
     #  done
     #else
     #  cd /tmp
@@ -167,10 +167,10 @@ function build_libtorrent_rasterbar () {
     #fi
 
     cd /tmp
-    git clone -b ${LTRC} https://github.com/arvidn/libtorrent.git >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: git could not clone the libtorrent repository"  >> "${SEEDIT_LOG}"  2>&1; exit 1; }
+    git clone -b ${LTRC} https://github.com/arvidn/libtorrent.git >> "${log}"  2>&1 || { echo "ERROR: git could not clone the libtorrent repository"  >> "${log}"  2>&1; exit 1; }
     cd libtorrent
-    ./autotool.sh >> "${SEEDIT_LOG}"  2>&1
-    ./configure --with-lib-geoip --with-libiconv >> "${SEEDIT_LOG}"  2>&1
+    ./autotool.sh >> "${log}"  2>&1
+    ./configure --with-lib-geoip --with-libiconv >> "${log}"  2>&1
     VERSION=$(grep "VERSION =" Jamfile | grep -oP '\d+.\d+.\d+')
     case $LTRC in
       RC_1_1)
@@ -180,15 +180,15 @@ function build_libtorrent_rasterbar () {
         sed -i 's|static constexpr reannounce_flags_t ignore_min_interval = 0_bit|static constexpr reannounce_flags_t ignore_min_interval = 1_bit|g' include/libtorrent/torrent_handle.hpp
       ;;
     esac
-    make -j$(nproc) >> "${SEEDIT_LOG}"  2>&1
+    make -j$(nproc) >> "${log}"  2>&1
     make DESTDIR=/tmp/dist/libtorrent install > /dev/null 2>&1
     mkdir -p /root/dist
     fpm -f -C /tmp/dist/libtorrent -p /root/dist/libtorrent-rasterbar_VERSION.deb -s dir -t deb -n libtorrent-rasterbar --version ${VERSION} --description "Libtorrent rasterbar compiled by swizzin" > /dev/null 2>&1
     dpkg -i /root/dist/libtorrent-rasterbar_${VERSION}.deb
     if [[ -n $deluge ]]; then
       echo "Building python binding ..."
-      PYTHON=${python} ./configure --enable-python-binding --with-libiconv ${configure_args} >> "${SEEDIT_LOG}"  2>&1
-      fpm --verbose --python-bin=${python} --python-package-name-prefix=${python} -n ${python}-libtorrent -f -p /root/dist/${python}-libtorrent_VERSION.deb --version ${VERSION} --description "Libtorrent rasterbar python bindings compiled by swizzin" -s python -t deb /tmp/libtorrent/bindings/python/setup.py >>  "${SEEDIT_LOG}"  2>&1
+      PYTHON=${python} ./configure --enable-python-binding --with-libiconv ${configure_args} >> "${log}"  2>&1
+      fpm --verbose --python-bin=${python} --python-package-name-prefix=${python} -n ${python}-libtorrent -f -p /root/dist/${python}-libtorrent_VERSION.deb --version ${VERSION} --description "Libtorrent rasterbar python bindings compiled by swizzin" -s python -t deb /tmp/libtorrent/bindings/python/setup.py >>  "${log}"  2>&1
       dpkg -i /root/dist/${python}-libtorrent_${VERSION}.deb
     fi
     ldconfig
@@ -201,10 +201,10 @@ function build_libtorrent_rasterbar () {
 
 function build_deluge () {
   if [[ $deluge == repo ]]; then
-    pip install --upgrade cryptography >> "${SEEDIT_LOG}"  2>&1
-    python -m easy_install --upgrade pyOpenSSL >> "${SEEDIT_LOG}"  2>&1
-    apt-get -q -y update >> "${SEEDIT_LOG}"  2>&1
-    apt-get -q -y install deluged deluge-web deluge-console >> "${SEEDIT_LOG}"  2>&1
+    pip install --upgrade cryptography >> "${log}"  2>&1
+    python -m easy_install --upgrade pyOpenSSL >> "${log}"  2>&1
+    apt-get -q -y update >> "${log}"  2>&1
+    apt-get -q -y install deluged deluge-web deluge-console >> "${log}"  2>&1
     chmod 644 /etc/swizzin/scripts/deluge.UpdateTracker.py
     cp /etc/swizzin/scripts/deluge.UpdateTracker.py /usr/lib/python2.7/dist-packages/deluge/ui/console/commands/update-tracker.py
     systemctl stop deluged
@@ -227,7 +227,7 @@ function build_deluge () {
     esac
     for depend in $LIST; do
       waitforapt
-      apt-get -qq -y install $depend >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${SEEDIT_LOG}"  2>&1; }
+      apt-get -qq -y install $depend >> "${log}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${log}"  2>&1; }
     done
     . /etc/swizzin/sources/functions/fpm
     install_fpm
@@ -242,13 +242,13 @@ function build_deluge () {
             mkdir -p /root/dist/python3
             for depend in $LIST; do
               waitforapt
-              apt-get -qq -y install $depend >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${SEEDIT_LOG}"  2>&1; }
+              apt-get -qq -y install $depend >> "${log}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${log}"  2>&1; }
             done
             for d in ${packages[@]}; do
               waitforapt
-              fpm -s python -t deb --python-pip=pip3 --python-bin=${pythonver} --python-package-name-prefix=${pythonver} -f -p /root/dist/python3/python3-$d.deb $d >>  "${SEEDIT_LOG}"  2>&1
+              fpm -s python -t deb --python-pip=pip3 --python-bin=${pythonver} --python-package-name-prefix=${pythonver} -f -p /root/dist/python3/python3-$d.deb $d >>  "${log}"  2>&1
               waitforapt
-              dpkg -i /root/dist/python3/python3-$d.deb >>  "${SEEDIT_LOG}"  2>&1
+              dpkg -i /root/dist/python3/python3-$d.deb >>  "${log}"  2>&1
             done
           ;;
           "stretch")
@@ -257,14 +257,14 @@ function build_deluge () {
             LIST='python3-twisted'
             for depend in $LIST; do
               waitforapt
-              apt-get -qq -y install -t stretch-backports $depend >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${SEEDIT_LOG}"  2>&1; }
+              apt-get -qq -y install -t stretch-backports $depend >> "${log}"  2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..." >>  "${log}"  2>&1; }
             done
           ;;
         esac
       fi
     fi
     cd /tmp
-    git clone -b ${deluge} git://deluge-torrent.org/deluge.git >> "${SEEDIT_LOG}"  2>&1 || { echo "WARN: Cloning Deluge from deluge-torrent.org failed, attempting github backup." >> "${SEEDIT_LOG}"  2>&1; git clone -b ${deluge} https://github.com/deluge-torrent/deluge/  >> "${SEEDIT_LOG}"  2>&1 || { echo "ERROR: Cloning Deluge from github failed" >> "${SEEDIT_LOG}"  2>&1; exit 1; } ; }
+    git clone -b ${deluge} git://deluge-torrent.org/deluge.git >> "${log}"  2>&1 || { echo "WARN: Cloning Deluge from deluge-torrent.org failed, attempting github backup." >> "${log}"  2>&1; git clone -b ${deluge} https://github.com/deluge-torrent/deluge/  >> "${log}"  2>&1 || { echo "ERROR: Cloning Deluge from github failed" >> "${log}"  2>&1; exit 1; } ; }
     cd deluge
     VERSION=$(git describe | cut -d- -f2)
     sed -i 's/-dev//g' setup.cfg
