sync functions

diff --git a/sources/functions/deluge b/sources/functions/deluge
--- a/sources/functions/deluge
+++ b/sources/functions/deluge
@@ -1,23 +1,28 @@
 #!/bin/bash
 
 function whiptail_deluge () {
-  if [[ -z $deluge ]]; then
-    repov=$(get_candidate_version deluge)
-    case $(lsb_release -cs) in
-    *)
-      function=$(whiptail --title "Install Software" --menu "Choose a Deluge version:" --ok-button "Continue" --nocancel 12 50 3 \
-                "Repo" "(${repov})" \
-                "Deluge 1.3" "" \
-                "Deluge 2.0" "" 3>&1 1>&2 2>&3)
-    ;;
-    esac
-    if [[ $function == "Repo" ]]; then
-      export deluge=repo
-    elif [[ $function == "Deluge 1.3" ]]; then
-      export deluge=1.3-stable
-    elif [[ $function == "Deluge 2.0" ]]; then
-    export deluge=master
-  fi
+    echo_progress_start "Choosing Deluge versions"
+	  if [[ -z $deluge ]]; then
+	    repov=$(get_candidate_version deluge)
+	    case $(lsb_release -cs) in
+	    *)
+	      function=$(whiptail --title "Install Software" --menu "Choose a Deluge version:" --ok-button "Continue" --nocancel 12 50 3 \
+	                "Repo" "(${repov})" \
+	                "Deluge 1.3" "" \
+	                "Deluge 2.0" "" 3>&1 1>&2 2>&3)
+	    ;;
+	    esac
+	    if [[ $function == "Repo" ]]; then
+	      export deluge=repo
+	    elif [[ $function == "Deluge 1.3" ]]; then
+	      export deluge=1.3-stable
+	    elif [[ $function == "Deluge 2.0" ]]; then
+	    export deluge=master
+	  fi
+    fi
+}
+
+function whiptail_deluge_downupgrade() {
     if [[ -n $(command -v deluged) ]]; then
       dverup=$(echo "$function" | sed 's|Deluge ||g' | cut -d. -f1)
       dvercurmajor=$(deluged -v | grep deluged | grep -oP '\d+\.\d+\.\d+' | cut -d. -f1)
@@ -32,19 +37,20 @@ function whiptail_deluge () {
   		  fi
       fi
     fi
-  fi
-
+    echo_progress_done
+    echo_log_only "deluge = $deluge"
 }
-
 function remove_ltcheckinstall () {
   oldv=$(apt-cache show libtorrent | grep checkinstall)
   if [[ -n $oldv ]]; then
-    echo "Removing checkinstall libtorrent"
+    echo_progress_start "Removing checkinstall libtorrent"
     dpkg -r libtorrent
+    echo_progress_done
   fi
 }
 
 function build_deluge () {
+  echo_progress_start "Building Deluge";
   if [[ $deluge == repo ]]; then
     apt_install deluged deluge-web deluge-console
     dver=$(deluged -v | grep deluged | grep -oP '\d+\.\d+\.\d+')
@@ -100,7 +106,7 @@ function build_deluge () {
       if [[ $twistedcheck == False ]] || [[ -z $twistedcheck ]]; then
         case $release in
           "xenial")
-            echo "Packaging up-to-date python3-twisted"
+            echo_progress_start "Packaging up-to-date python3-twisted"
             LIST='libffi-dev python3-pip'
             packages=(setuptools pycparser asn1crypto cffi constantly incremental attrs automat idna hyperlink pyhamcrest cryptography pyopenssl service_identity zope.interface twisted)
             mkdir -p /root/dist/python3
@@ -109,6 +115,7 @@ function build_deluge () {
               /usr/local/bin/fpm -s python -t deb --python-pip=pip3 --python-bin=${pythonver} --python-package-name-prefix=${pythonver} -f -p /root/dist/python3/python3-$d.deb $d >> ${log} 2>&1
               dpkg -i /root/dist/python3/python3-$d.deb >> ${log} 2>&1
             done
+            echo_progress_done "Packaging finished"
           ;;
           "stretch")
             . /etc/swizzin/sources/functions/backports
@@ -124,7 +131,7 @@ function build_deluge () {
       fi
     fi
     cd /tmp
-    git clone -b ${deluge} git://deluge-torrent.org/deluge.git >>"${log}" 2>&1 || { echo "WARN: Cloning Deluge from deluge-torrent.org failed, attempting github backup."; git clone -b ${deluge} https://github.com/deluge-torrent/deluge/ >>"${log}" 2>&1 || { echo "ERROR: Cloning Deluge from github failed"; exit 1; } ; }
+    git clone -b ${deluge} git://deluge-torrent.org/deluge.git >>"${log}" 2>&1 || { echo_warn "Cloning Deluge from deluge-torrent.org failed, attempting github backup."; git clone -b ${deluge} https://github.com/deluge-torrent/deluge/ >>"${log}" 2>&1 || { echo_error "Cloning Deluge from github failed"; exit 1; } ; }
     cd deluge
     VERSION=$(git describe | cut -d- -f2)
     sed -i 's/-dev//g' setup.cfg
@@ -141,6 +148,7 @@ function build_deluge () {
     rm -rf deluge
     apt-mark hold deluge-common
   fi
+  echo_progress_done "Deluge installed"
 }
 
 function dweb_check () {
@@ -221,11 +229,12 @@ function ltconfig () {
 }
 
 function cleanup_deluge () {
+  echo_progress_start "Performing cleanup"
   toclean=(deluge-common deluge-web deluged deluge-console)
   for p in ${toclean[@]}; do
     if dpkg -l | grep $p > /dev/null 2>&1; then
-      echo "Cleaning package: $p. Removing."
       dpkg -r $p > /dev/null 2>&1
     fi
   done
+  echo_progress_done
 }
diff --git a/sources/functions/libtorrent b/sources/functions/libtorrent
--- a/sources/functions/libtorrent
+++ b/sources/functions/libtorrent
@@ -9,7 +9,7 @@ function whiptail_libtorrent_rasterbar () {
         case $(lsb_release -cs) in
             "xenial"|"focal")
                 function="1.1"
-                echo "Defaulting to libtorrent branch RC_1_1 for shared compatbility"
+                echo_info "Defaulting to libtorrent branch RC_1_1 for shared compatbility"
                 ;;
             *)
                 function=$(whiptail --title "Install Software" --menu "Choose a libtorrent branch:" --ok-button "Continue" --nocancel 12 50 3 \
@@ -123,7 +123,7 @@ function build_libtorrent_rasterbar () {
     cleanup=(python3-libtorrent python-libtorrent libtorrent-rasterbar libtorrent-rasterbar-dev)
     for a in ${cleanup[@]}; do
       if dpkg -l | grep $a | grep swizzin > /dev/null 2>&1; then
-        echo "Found $a. Removing."
+        echo_info "Found $a. Removing."
         dpkg -r $a > /dev/null 2>&1
       fi
     done
@@ -184,7 +184,7 @@ function build_libtorrent_rasterbar () {
     cleanup=($remove libtorrent-rasterbar7 libtorrent-rasterbar8 libtorrent-rasterbar9)
     for a in ${cleanup[@]}; do
       if dpkg -l | grep $a > /dev/null 2>&1; then
-        echo "Found package conflict: $a. Removing."
+        echo_info "Found package conflict: $a. Removing."
         dpkg -r $a > /dev/null 2>&1
       fi
     done
@@ -207,7 +207,7 @@ function build_libtorrent_rasterbar () {
         swap=true
         tmp_swap_on
     fi
-    git clone -b ${LTRC} https://github.com/arvidn/libtorrent.git >>"${log}" 2>&1 || { echo "ERROR: git could not clone the libtorrent repository"; exit 1; }
+    git clone -b ${LTRC} https://github.com/arvidn/libtorrent.git >>"${log}" 2>&1 || { echo_error "ERROR: git could not clone the libtorrent repository"; exit 1; }
     cd libtorrent
     if [[ ! $LTRC =~ ("RC_1_0"|"RC_1_1") ]]; then
         configure_args="-std=c++14"
@@ -240,10 +240,11 @@ function build_libtorrent_rasterbar () {
     /usr/local/bin/fpm -f -C /tmp/dist/libtorrent -p /root/dist/libtorrent-rasterbar_VERSION.deb -s dir -t deb -n libtorrent-rasterbar --version ${VERSION} --description "Libtorrent rasterbar compiled by swizzin$tag" > /dev/null 2>&1
     dpkg -i /root/dist/libtorrent-rasterbar_${VERSION}.deb
     if [[ -n $deluge ]]; then
-      echo "Building python binding ..."
+      echo_progress_start "Building python binding"
       PYTHON=${pythonbin} ./configure --enable-python-binding --with-libiconv ${python_configure_args} CXXFLAGS=${configure_args} >>"${log}" 2>&1
       /usr/local/bin/fpm --verbose --python-bin=${pythonbin} --python-package-name-prefix=${python} -n ${python}-libtorrent -f -p /root/dist/${python}-libtorrent_VERSION.deb --version ${VERSION} --description "Libtorrent rasterbar python bindings compiled by swizzin$tag" -s python -t deb /tmp/libtorrent/bindings/python/setup.py >> $log 2>&1
       dpkg -i /root/dist/${python}-libtorrent_${VERSION}.deb
+      echo_progress_done "Pbox ython binding built"
     fi
     ldconfig
     cd /tmp
