lolsalt

diff --git a/scripts/box b/scripts/box
--- a/scripts/box
+++ b/scripts/box
@@ -191,33 +191,21 @@ function _list() {
 }
 
 function _adduser {
+  if [[ -z $2 ]]; then
+    echo "Error: You must specify a user"
+    exit 1
+  fi
   user=$2
   if [[ $user =~ [A-Z] ]]; then
     echo "Usernames must not contain capital letters. Please try again."
     exit 1
   fi
-
-  if [[ -f /root/${user}.info ]]; then
-    echo "User already seems to exist"
-    exit 1
-  fi
-
-  id -u ${user} > /dev/null 2>&1
-  existing=$?
-
-  if [[ $existing == 0 ]]; then
-    echo "${user} already appears to be present on this machine; however, it does not appear to be configured as a swizzin user"
-    echo
-    read -rep 'Press enter to continue adding user.'
-    echo
-  fi
-
   echo -e "Enter password for ${user}. (leave empty to generate a password)"; read 'pass'
   if [[ -z "${pass}" ]]; then
     pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
     echo "Password for ${user} has been set to ${pass}"
   fi
-  if [[ -n $(which cracklib-check) ]]; then 
+  if [[ -n $(which cracklib-check) ]]; then
     echo "Cracklib detected. Checking password strength."
     sleep 1
     str="$(cracklib-check <<<"$pass")"
@@ -231,9 +219,7 @@ function _adduser {
     fi
   fi
   echo "$user:$pass" > /root/${user}.info
-  if [[ $existing == 1 ]]; then
   useradd "${user}" -m -G www-data -s /bin/bash
-  fi
   chpasswd<<<"${user}:${pass}"
   htpasswd -b /etc/htpasswd $user $pass
   mkdir -p /etc/htpasswd.d/
@@ -286,20 +272,8 @@ fi
 
 function _deluser {
   user=$2
-  if [[ ! -f /root/${user}.info ]]; then
-    master=$(cut -d: -f1 < /root/.master.info)
-    if [[ $user == $master ]]; then
-      echo "Master user deletion is not supported"
-      exit 1
-    fi
-    echo "Error: user ${user} not found. Exiting."
-    exit 1
-  fi
+  read -rep $'WARNING: This will delete the user '${user}' and all associated configs and subdirectories.\n\nPress enter to continue.'
 
-  echo "WARNING: This will delete the user '${user}' and all associated configs and subdirectories. THIS ACTION CANNOT BE UNDONE."
-  echo
-  read -rep 'Removal will start as soon as you confirm this message. Press enter to continue.'
-  
   for app in rtorrent rutorrent deluge autodl flood nzbget lounge; do
     if [[ $app = "rutorrent" ]]; then
       if [[ -d /srv/rutorrent ]]; then
@@ -325,7 +299,7 @@ function _deluser {
       fi
     fi
   done
-  
+
   if [[ -z $(which lsof) ]]; then
     apt-get install -y -q lsof > /dev/null 2>&1
   fi
@@ -346,25 +320,8 @@ function _deluser {
 
 function _chpasswd {
   user=$2
-  echo -e "Enter new password for ${user}. Leave empty to generate a password"; read 'pass'
-  if [[ -z "${pass}" ]]; then
-    pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
-    echo "New password has been set to ${pass}"
-  fi
-  if [[ -n $(which cracklib-check) ]]; then 
-    echo "Cracklib detected. Checking password strength."
-    sleep 1
-    str="$(cracklib-check <<<"$pass")"
-    check=$(grep OK <<<"$str")
-    if [[ -z $check ]]; then
-      read -n 1 -s -r -p "Password did not pass cracklib check. Press any key to enter a new password"
-      printf "\n"
-      _chpasswd "$@"
-    else
-      echo "OK"
-    fi
-  fi
-  master=$(cut -d: -f1 < /root/.master.info)
+  pass=$3
+  master=$(cat /root/.master.info | cut -d: -f1)
   if [[ $user = $master ]]; then
     echo "$user:$pass" > /root/.master.info
   fi
