misc sync

diff --git a/scripts/box b/scripts/box
--- a/scripts/box
+++ b/scripts/box
@@ -254,8 +254,28 @@ function _adduser {
   if [[ $user =~ [A-Z] ]]; then
     echo "Usernames must not contain capital letters. Please try again."
     exit 1
+  elif [[ $user =~ ("swizzin"|"admin") ]]; then
+    echo "$user is a reserved username -- please use something else."
+    exit 1
   fi
+
+  if [[ -f /root/${user}.info ]]; then
+    echo "User already seems to exist"
+    exit 1
+  fi
+
+  id -u ${user} > /dev/null 2>&1
+  existing=$?
+
+  if [[ $existing == 0 ]]; then
+    echo "${user} already appears to be present on this machine; however, it does not appear to be configured as a swizzin user"
+    echo
+    read -rep 'Press enter to continue adding user.'
+    echo
+  fi
+
   echo -e "Enter password for ${user}. (leave empty to generate a password)"; read 'pass'
+
   if [[ -z "${pass}" ]]; then
     pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
     echo "Password for ${user} has been set to ${pass}"
@@ -274,7 +294,9 @@ function _adduser {
     fi
   fi
   echo "$user:$pass" > /root/${user}.info
+  if [[ $existing == 1 ]]; then
   useradd "${user}" -m -G www-data -s /bin/bash
+  fi
   chpasswd<<<"${user}:${pass}"
   htpasswd -b /etc/htpasswd $user $pass
   mkdir -p /etc/htpasswd.d/
@@ -483,58 +505,6 @@ function _nukeovh() {
   fi
 }
 
-#function waitforapt {
-#
-#  if [[ -f /install/.tools.lock ]]; then
-#    export log=/srv/tools/logs/output.log
-#  else
-#    export log=/root/logs/install.log
-#  fi
-#
-#
-#  i=0
-#  echo "waiting for apt locks"
-#  echo "waiting for apt locks"  >> "${log}" 2>&1;
-#  while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
-#    ((i++))
-#
-#    if [ $i -lt 30 ]; then
-#      expr 30 - $i
-#      expr 30 - $i >> "${log}" 2>&1;
-#    fi
-#
-#    if [ $i == 30 ]; then
-#      echo "killall apt-get"
-#      echo "killall apt-get" >> "${log}" 2>&1;
-#      echo "waiting another 30 seconds till i delete locks"
-#      echo "waiting another 30 seconds till i delete locks" >> "${log}" 2>&1;
-#      sudo killall apt-get >> "${log}" 2>&1;
-#    fi
-#
-#    if [ $i -gt 30 ]; then
-#      expr 60 - $i
-#      expr 60 - $i >> "${log}" 2>&1;
-#    fi
-#
-#    if [ $i == 60 ]; then
-#      echo "deleting locks"
-#      echo "deleting locks" >> "${log}" 2>&1;
-#      sudo rm /var/lib/dpkg/lock
-#      sudo rm /var/lib/dpkg/lock-frontend
-#      sudo rm /var/cache/apt/archives/lock
-#      sudo rm /var/cache/debconf/*.dat
-#
-#      sudo rm /var/lib/apt/lists/lock
-#      sudo rm /var/cache/apt/archives/lock
-#      sudo rm /var/lib/dpkg/updates/*
-#      #sudo apt-get update
-#    fi
-#
-#    sleep 1
-#
-#  done
-#}
-
 normal=$(tput sgr0)
 yellow=$(tput setaf 3)
 bold=$(tput bold)
@@ -576,6 +546,10 @@ case "$1" in
     exit 0
   ;;
   "adduser")
+    if [[ -z $2 ]]; then
+      echo "Error: You must specify a user"
+      exit 1
+    fi
     if [[ -n $3 ]]; then
       echo -e "Error: too many arguments\nCorrect usage: box adduser <username>"
       exit 1
@@ -584,6 +558,10 @@ case "$1" in
   exit 0
   ;;
   "deluser")
+    if [[ -z $2 ]]; then
+      echo -e "Error: you must specify a username.\nCorrect usage: box deluser <username>"
+      exit 1
+    fi
     if [[ -n $3 ]]; then
       echo -e "Error: too many arguments\nCorrect usage: box deluser <username>"
       exit 1
@@ -625,3 +603,4 @@ case "$1" in
     exit 1
   ;;
 esac
+
